// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVDgWqI1cSiqh_nB1ctJIi2EhfY1kkSYY',
    appId: '1:997913142383:web:18ed82467c63555645999a',
    messagingSenderId: '997913142383',
    projectId: 'lunet-project',
    authDomain: 'lunet-project.firebaseapp.com',
    storageBucket: 'lunet-project.firebasestorage.app',
    measurementId: 'G-1N1B57S2VG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7WebAlDRU0PufBpC-pXy4sfbooh7D7kE',
    appId: '1:997913142383:android:cee9180c6384ad0045999a',
    messagingSenderId: '997913142383',
    projectId: 'lunet-project',
    storageBucket: 'lunet-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVGknvdRT4qD4N0sx5Lb63nsVw-T0YViw',
    appId: '1:997913142383:ios:80646296eaae672345999a',
    messagingSenderId: '997913142383',
    projectId: 'lunet-project',
    storageBucket: 'lunet-project.firebasestorage.app',
    iosBundleId: 'com.example.lunetProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVGknvdRT4qD4N0sx5Lb63nsVw-T0YViw',
    appId: '1:997913142383:ios:80646296eaae672345999a',
    messagingSenderId: '997913142383',
    projectId: 'lunet-project',
    storageBucket: 'lunet-project.firebasestorage.app',
    iosBundleId: 'com.example.lunetProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVDgWqI1cSiqh_nB1ctJIi2EhfY1kkSYY',
    appId: '1:997913142383:web:c65694707f78059845999a',
    messagingSenderId: '997913142383',
    projectId: 'lunet-project',
    authDomain: 'lunet-project.firebaseapp.com',
    storageBucket: 'lunet-project.firebasestorage.app',
    measurementId: 'G-ZTP09FD468',
  );
}
